# Generated by Django 4.1.6 on 2023-03-23 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("manager", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="investing",
            name="amount",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        )
    ]
